'use client';

import React, { useState, useEffect } from 'react';
import { User, Check, Sparkles, X, ShieldCheck } from 'lucide-react';
import { useAuth } from '../lib/auth-context';
import { useApp } from '../lib/app-context';

export function NameSetupModal() {
  const { user: authUser, updateProfile } = useAuth();
  const { profilePrefs, setProfilePrefs } = useApp();
  const [open, setOpen] = useState(false);
  const [name, setName] = useState('');
  const [role, setRole] = useState<'INDIVIDUAL' | 'STUDENT' | 'PROFESSIONAL' | 'INSTITUTION'>('INDIVIDUAL');
  const [institution, setInstitution] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!authUser) return;

    // Check if user has already explicitly configured their real name
    const alreadyConfigured = typeof window !== 'undefined' ? localStorage.getItem('resolvia_name_configured') : null;
    if (alreadyConfigured === 'true') return;

    // Detect if name looks like an uncustomized username (e.g. Yash82040, user_123, or email prefix)
    const emailPrefix = authUser.email ? authUser.email.split('@')[0].toLowerCase() : '';
    const currentName = (authUser.name || '').trim();
    const isAutoGenerated =
      !currentName ||
      currentName.toLowerCase() === emailPrefix ||
      /\d{3,}/.test(currentName) || // contains 3+ digits like Yash82040
      currentName === 'Community Member' ||
      currentName === 'Alex Vance' ||
      currentName === 'Resolvia Arbiter';

    if (isAutoGenerated) {
      // Suggest a cleaner default title-cased name from email without numbers
      const cleanSuggestion = emailPrefix.replace(/\d+/g, '').replace(/[._-]/g, ' ').trim();
      const suggested = cleanSuggestion
        ? cleanSuggestion.replace(/\b\w/g, (c) => c.toUpperCase())
        : currentName || 'Resolvia Arbiter';

      setName(suggested);
      setInstitution(profilePrefs.institution || '');
      setRole((profilePrefs.roleType as any) || 'INDIVIDUAL');
      setOpen(true);
    }
  }, [authUser, profilePrefs]);

  const handleSave = async () => {
    const trimmed = name.trim();
    if (!trimmed) return;
    setSaving(true);
    try {
      if (updateProfile) {
        await updateProfile({ name: trimmed });
      }
      if (typeof window !== 'undefined') {
        localStorage.setItem('resolvia_user_name', trimmed);
        localStorage.setItem('resolvia_name_configured', 'true');
      }
      setProfilePrefs({
        ...profilePrefs,
        roleType: role,
        institution: institution.trim() || profilePrefs.institution,
      });
      setOpen(false);
    } catch {
      // Continue even if backend has network lag
      setOpen(false);
    } finally {
      setSaving(false);
    }
  };

  const handleDismiss = () => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('resolvia_name_configured', 'true');
    }
    setOpen(false);
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fade-in">
      <div className="relative w-full max-w-md bg-white rounded-3xl shadow-2xl border border-slate-200 overflow-hidden text-slate-900">
        {/* Header Ribbon */}
        <div className="bg-gradient-to-r from-violet-600 via-indigo-600 to-violet-700 px-6 py-6 text-white relative">
          <button
            onClick={handleDismiss}
            className="absolute top-4 right-4 p-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-white transition-colors cursor-pointer"
            title="Close"
          >
            <X className="w-4 h-4" />
          </button>
          <div className="w-12 h-12 rounded-2xl bg-white/20 backdrop-blur-md flex items-center justify-center mb-3 ring-4 ring-white/10">
            <Sparkles className="w-6 h-6 text-white" />
          </div>
          <h2 className="text-xl font-black tracking-tight">Welcome to Resolvia!</h2>
          <p className="text-xs text-violet-100 mt-1 leading-relaxed">
            Please enter your official display name. This name will be displayed on your cases, jury ballots, and verified profile.
          </p>
        </div>

        {/* Content Form */}
        <div className="p-6 space-y-4">
          <div>
            <label className="text-[11px] font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5 mb-1.5">
              <User className="w-3.5 h-3.5 text-violet-600" /> Full Display Name
            </label>
            <input
              type="text"
              autoFocus
              value={name}
              onChange={(e) => setName(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSave()}
              placeholder="e.g. Yash Vijay Singh"
              className="w-full px-3.5 py-3 rounded-xl border border-slate-300 bg-white text-slate-900 placeholder:text-slate-400 text-sm font-semibold outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 shadow-xs transition-all"
            />
            <p className="text-[11px] text-slate-400 mt-1">
              You can change this anytime later in Settings or Profile.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-[11px] font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
                Role
              </label>
              <select
                value={role}
                onChange={(e) => setRole(e.target.value as any)}
                className="w-full px-3 py-2.5 rounded-xl border border-slate-300 bg-white text-slate-900 text-xs font-semibold outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 shadow-xs cursor-pointer"
              >
                <option value="INDIVIDUAL">Individual</option>
                <option value="STUDENT">Student</option>
                <option value="PROFESSIONAL">Professional</option>
                <option value="INSTITUTION">Institution</option>
              </select>
            </div>
            <div>
              <label className="text-[11px] font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
                Institution / City
              </label>
              <input
                type="text"
                value={institution}
                onChange={(e) => setInstitution(e.target.value)}
                placeholder="e.g. Mumbai, India"
                className="w-full px-3 py-2.5 rounded-xl border border-slate-300 bg-white text-slate-900 placeholder:text-slate-400 text-xs font-semibold outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20 shadow-xs"
              />
            </div>
          </div>

          <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-100 flex items-center gap-2.5 text-emerald-800 text-[11px]">
            <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>Decentralized Identity: Verified on-chain via platform wallet.</span>
          </div>

          <div className="flex items-center gap-3 pt-2">
            <button
              onClick={handleSave}
              disabled={!name.trim() || saving}
              className="flex-1 py-3 px-4 rounded-xl bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white text-xs font-black transition-all shadow-lg shadow-violet-900/20 cursor-pointer flex items-center justify-center gap-2"
            >
              <Check className="w-4 h-4" />
              <span>{saving ? 'Saving…' : 'Set Display Name'}</span>
            </button>
            <button
              onClick={handleDismiss}
              className="px-4 py-3 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-600 text-xs font-bold transition-colors cursor-pointer"
            >
              Skip
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
